
CONTROL_PARAM_VALUE.MASS_LOAD = 0.5; % kg
CONTROL_PARAM_VALUE.MASS_UAV = 1.5; % kg
CONTROL_PARAM_VALUE.CABLE_LEN = 1; % m

CONTROL_PARAM_VALUE.KP = 0.2; % Kp
CONTROL_PARAM_VALUE.KV = 4; % Kv 4
CONTROL_PARAM_VALUE.KQ = 1; % Kq 1
CONTROL_PARAM_VALUE.KW = 5; % Kw 5
% Export
CONTROL_PARAM = Simulink.Parameter(CONTROL_PARAM_VALUE);
CONTROL_PARAM.CoderInfo.StorageClass = 'ExportedGlobal';