
CONTROL_PARAM_VALUE.MASS_LOAD = 0.06; % kg
CONTROL_PARAM_VALUE.MASS_UAV = 0.21; % kg
CONTROL_PARAM_VALUE.CABLE_LEN = 0.6; % m

CONTROL_PARAM_VALUE.KP = 0.5; % Kp
CONTROL_PARAM_VALUE.KV = 4; % Kv 0.4
CONTROL_PARAM_VALUE.KQ = 5; % Kq 5
CONTROL_PARAM_VALUE.KW = 1; % Kw 1
% Export
CONTROL_PARAM = Simulink.Parameter(CONTROL_PARAM_VALUE);
CONTROL_PARAM.CoderInfo.StorageClass = 'ExportedGlobal';